version: "3.3"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

  python:
    build: .
    volumes:
      - .:/code
    environment:
      TZ: Europe/Moscow
    ports:
      - "8001:8000"
